In [44]:
import numpy as np

In [45]:
# %pip install numpy pandas matplotlib seaborn scikit-learn tensorflow jupyter ipykernel

In [46]:
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [47]:
df = pd.read_csv("plant_water_data_1000.csv")

In [48]:
df

     soil_moisture  temperature_c  sunlight_hours  needs_water
0             0.37             32               2            1
1             0.86             29               5            0
2             0.67             33               4            0
3             0.56             25              11            0
4             0.18             34               2            1
..             ...            ...             ...          ...
995           0.13             29               3            1
996           0.83             28               6            0
997           0.17             28              10            1
998           0.86             30              10            0
999           0.43             35               5            1

[1000 rows x 4 columns]

In [49]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='str')

In [50]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df[['needs_water']]

In [51]:
X_min = X.min()
X_max = X.max()
X_scaled = (X -X_min)/(X_max - X_min +1e-8)

In [52]:
X_scaled

     soil_moisture  temperature_c  sunlight_hours
0         0.376471       0.823529        0.090909
1         0.952941       0.647059        0.363636
2         0.729412       0.882353        0.272727
3         0.600000       0.411765        0.909091
4         0.152941       0.941176        0.090909
..             ...            ...             ...
995       0.094118       0.647059        0.181818
996       0.917647       0.588235        0.454545
997       0.141176       0.588235        0.818182
998       0.952941       0.705882        0.818182
999       0.447059       1.000000        0.363636

[1000 rows x 3 columns]

In [53]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

In [54]:
model  = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(3,activation='softmax')
])

In [57]:
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [61]:
history_full = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=len(X_train),
    verbose=1
)

Epoch 1/100

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5907 - loss: 0.7179
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5920 - loss: 0.7160
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5920 - loss: 0.7142
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5920 - loss: 0.7123
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5920 - loss: 0.7105
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5933 - loss: 0.7086
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5933 - loss: 0.7068
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5933 - loss: 0.7050
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5933 - loss: 0.7032
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5933 - loss: 0.7015
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5947 - loss: 0.6997
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5973 - loss: 0.6980
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5973 - loss: 0.6963
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5973 - loss: 0.6946
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6000 - loss: 0.6929
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6013 - loss: 0.6912
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6027 - loss: 0.6896
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6027 - loss: 0.6879
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6027 - loss: 0.6863
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6027 - loss: 0.6847
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6067 - loss: 0.6831
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6080 - loss: 0.6816
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6093 - loss: 0.6800
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6107 - loss: 0.6785
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6133 - loss: 0.6770
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6147 - loss: 0.6754
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6147 - loss: 0.6740
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.6160 - loss: 0.6725
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6160 - loss: 0.6710
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6160 - loss: 0.6696
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6173 - loss: 0.6682
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6187 - loss: 0.6667
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6187 - loss: 0.6653
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6213 - loss: 0.6640
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6227 - loss: 0.6626
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6240 - loss: 0.6612
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6240 - loss: 0.6599
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6240 - loss: 0.6586
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6253 - loss: 0.6573
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6267 - loss: 0.6560
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6267 - loss: 0.6547
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6280 - loss: 0.6534
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6280 - loss: 0.6522
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6280 - loss: 0.6510
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6280 - loss: 0.6497
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6347 - loss: 0.6485
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6360 - loss: 0.6473
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6360 - loss: 0.6462
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.6360 - loss: 0.6450
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6347 - loss: 0.6439
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6347 - loss: 0.6427
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6347 - loss: 0.6416
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6347 - loss: 0.6405
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6347 - loss: 0.6394
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6347 - loss: 0.6383
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6360 - loss: 0.6372
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6373 - loss: 0.6362
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6373 - loss: 0.6351
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6373 - loss: 0.6341
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6373 - loss: 0.6331
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6400 - loss: 0.6320
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6400 - loss: 0.6311
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6400 - loss: 0.6301
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6413 - loss: 0.6291
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6400 - loss: 0.6281
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6413 - loss: 0.6272
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6427 - loss: 0.6262
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6453 - loss: 0.6253
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6467 - loss: 0.6244
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6480 - loss: 0.6235
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6493 - loss: 0.6226
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6493 - loss: 0.6217
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6520 - loss: 0.6209
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6533 - loss: 0.6200
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6533 - loss: 0.6191
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6560 - loss: 0.6183
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6587 - loss: 0.6175
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6573 - loss: 0.6167
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6573 - loss: 0.6158
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6587 - loss: 0.6150
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6587 - loss: 0.6143
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6587 - loss: 0.6135
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6600 - loss: 0.6127
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6600 - loss: 0.6120
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6600 - loss: 0.6112
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6613 - loss: 0.6105
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6667 - loss: 0.6097
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.6090
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6680 - loss: 0.6083
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6680 - loss: 0.6076
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6693 - loss: 0.6069
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6693 - loss: 0.6062
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6733 - loss: 0.6055
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6733 - loss: 0.6049
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6747 - loss: 0.6042
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6747 - loss: 0.6035
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6773 - loss: 0.6029
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6773 - loss: 0.6023
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6773 - loss: 0.6016
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6773 - loss: 0.6010

In [62]:
history = model.fit(
    X_train.values,
    y_train.values,
    validation_data=(X_test.values, y_test.values),
    epochs=100,
    batch_size=1,
    verbose=1
)

Epoch 1/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7533 - loss: 0.5586 - val_accuracy: 0.9560 - val_loss: 0.4770
Epoch 2/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7867 - loss: 0.4877 - val_accuracy: 0.8800 - val_loss: 0.4324
Epoch 3/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8520 - loss: 0.4212 - val_accuracy: 0.7040 - val_loss: 0.4493
Epoch 4/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8920 - loss: 0.3665 - val_accuracy: 0.9680 - val_loss: 0.3094
Epoch 5/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9040 - loss: 0.3367 - val_accuracy: 0.8720 - val_loss: 0.3071
Epoch 6/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9187 - loss: 0.2919 - val_accuracy: 0.8840 - val_loss: 0.2766
Epoch 7/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9253 - loss: 0.2700 - val_accuracy: 0.9520 - val_loss: 0.2271
Epoch 8/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9467 - loss: 0.2412 - val_accuracy: 0.9640 - val_loss: 0.1989
Epoch 9/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9453 - loss: 0.2242 - val_accuracy: 0.9520 - val_loss: 0.1900
Epoch 10/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9427 - loss: 0.2053 - val_accuracy: 0.9640 - val_loss: 0.1730
Epoch 11/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9467 - loss: 0.1930 - val_accuracy: 0.9440 - val_loss: 0.1688
Epoch 12/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9507 - loss: 0.1799 - val_accuracy: 0.9600 - val_loss: 0.1453
Epoch 13/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9547 - loss: 0.1724 - val_accuracy: 0.9600 - val_loss: 0.1411
Epoch 14/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9480 - loss: 0.1671 - val_accuracy: 0.9120 - val_loss: 0.1839
Epoch 15/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9507 - loss: 0.1591 - val_accuracy: 0.9600 - val_loss: 0.1248
Epoch 16/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9520 - loss: 0.1493 - val_accuracy: 0.9640 - val_loss: 0.1175
Epoch 17/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9573 - loss: 0.1407 - val_accuracy: 0.9480 - val_loss: 0.1307
Epoch 18/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9613 - loss: 0.1390 - val_accuracy: 0.9440 - val_loss: 0.1411
Epoch 19/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9600 - loss: 0.1338 - val_accuracy: 0.9640 - val_loss: 0.1064
Epoch 20/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9480 - loss: 0.1356 - val_accuracy: 0.9600 - val_loss: 0.1013
Epoch 21/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9613 - loss: 0.1241 - val_accuracy: 0.9600 - val_loss: 0.1005
Epoch 22/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9613 - loss: 0.1194 - val_accuracy: 0.9320 - val_loss: 0.1391
Epoch 23/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9720 - loss: 0.1187 - val_accuracy: 0.9680 - val_loss: 0.0939
Epoch 24/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9667 - loss: 0.1147 - val_accuracy: 0.9720 - val_loss: 0.0919
Epoch 25/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9747 - loss: 0.1077 - val_accuracy: 0.9680 - val_loss: 0.0906
Epoch 26/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9560 - loss: 0.1126 - val_accuracy: 0.9680 - val_loss: 0.0934
Epoch 27/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9693 - loss: 0.1028 - val_accuracy: 0.9640 - val_loss: 0.0884
Epoch 28/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9600 - loss: 0.1055 - val_accuracy: 0.9600 - val_loss: 0.0841
Epoch 29/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9627 - loss: 0.1026 - val_accuracy: 0.9640 - val_loss: 0.0877
Epoch 30/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9573 - loss: 0.1067 - val_accuracy: 0.9640 - val_loss: 0.0858
Epoch 31/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9613 - loss: 0.0994 - val_accuracy: 0.9440 - val_loss: 0.1043
Epoch 32/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9640 - loss: 0.1000 - val_accuracy: 0.9680 - val_loss: 0.0780
Epoch 33/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9587 - loss: 0.0985 - val_accuracy: 0.9640 - val_loss: 0.0795
Epoch 34/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9707 - loss: 0.0917 - val_accuracy: 0.9360 - val_loss: 0.1339
Epoch 35/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9600 - loss: 0.0966 - val_accuracy: 0.9680 - val_loss: 0.0938
Epoch 36/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9680 - loss: 0.0897 - val_accuracy: 0.9640 - val_loss: 0.0759
Epoch 37/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9680 - loss: 0.0924 - val_accuracy: 0.9720 - val_loss: 0.0737
Epoch 38/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9667 - loss: 0.0927 - val_accuracy: 0.9440 - val_loss: 0.1138
Epoch 39/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9640 - loss: 0.0948 - val_accuracy: 0.9560 - val_loss: 0.0930
Epoch 40/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9693 - loss: 0.0872 - val_accuracy: 0.9640 - val_loss: 0.0839
Epoch 41/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9680 - loss: 0.0883 - val_accuracy: 0.9720 - val_loss: 0.0735
Epoch 42/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9707 - loss: 0.0802 - val_accuracy: 0.9680 - val_loss: 0.0706
Epoch 43/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9680 - loss: 0.0805 - val_accuracy: 0.9360 - val_loss: 0.1244
Epoch 44/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9747 - loss: 0.0814 - val_accuracy: 0.9680 - val_loss: 0.0779
Epoch 45/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9680 - loss: 0.0822 - val_accuracy: 0.9720 - val_loss: 0.0714
Epoch 46/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9707 - loss: 0.0814 - val_accuracy: 0.9720 - val_loss: 0.0750
Epoch 47/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9640 - loss: 0.0838 - val_accuracy: 0.9640 - val_loss: 0.0671
Epoch 48/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9733 - loss: 0.0760 - val_accuracy: 0.9680 - val_loss: 0.0830
Epoch 49/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9747 - loss: 0.0802 - val_accuracy: 0.9640 - val_loss: 0.0635
Epoch 50/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9707 - loss: 0.0770 - val_accuracy: 0.9720 - val_loss: 0.0732
Epoch 51/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9707 - loss: 0.0793 - val_accuracy: 0.9680 - val_loss: 0.0647
Epoch 52/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9667 - loss: 0.0801 - val_accuracy: 0.9760 - val_loss: 0.0613
Epoch 53/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9733 - loss: 0.0776 - val_accuracy: 0.9640 - val_loss: 0.0868
Epoch 54/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9693 - loss: 0.0721 - val_accuracy: 0.9760 - val_loss: 0.0628
Epoch 55/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9760 - loss: 0.0719 - val_accuracy: 0.9760 - val_loss: 0.0644
Epoch 56/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9627 - loss: 0.0830 - val_accuracy: 0.9720 - val_loss: 0.0609
Epoch 57/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9693 - loss: 0.0748 - val_accuracy: 0.9680 - val_loss: 0.0604
Epoch 58/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9720 - loss: 0.0701 - val_accuracy: 0.9680 - val_loss: 0.0771
Epoch 59/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9640 - loss: 0.0701 - val_accuracy: 0.9680 - val_loss: 0.0605
Epoch 60/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9720 - loss: 0.0660 - val_accuracy: 0.9680 - val_loss: 0.0580
Epoch 61/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9747 - loss: 0.0732 - val_accuracy: 0.9080 - val_loss: 0.1877
Epoch 62/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9720 - loss: 0.0705 - val_accuracy: 0.9720 - val_loss: 0.0616
Epoch 63/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9747 - loss: 0.0679 - val_accuracy: 0.9480 - val_loss: 0.1151
Epoch 64/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9720 - loss: 0.0725 - val_accuracy: 0.9760 - val_loss: 0.0635
Epoch 65/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9720 - loss: 0.0705 - val_accuracy: 0.9760 - val_loss: 0.0560
Epoch 66/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9760 - loss: 0.0624 - val_accuracy: 0.9440 - val_loss: 0.1038
Epoch 67/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9773 - loss: 0.0655 - val_accuracy: 0.9720 - val_loss: 0.0689
Epoch 68/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9667 - loss: 0.0752 - val_accuracy: 0.9400 - val_loss: 0.1128
Epoch 69/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9733 - loss: 0.0617 - val_accuracy: 0.9800 - val_loss: 0.0562
Epoch 70/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9693 - loss: 0.0706 - val_accuracy: 0.9760 - val_loss: 0.0599
Epoch 71/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9733 - loss: 0.0654 - val_accuracy: 0.9760 - val_loss: 0.0620
Epoch 72/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9720 - loss: 0.0661 - val_accuracy: 0.9760 - val_loss: 0.0553
Epoch 73/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9800 - loss: 0.0584 - val_accuracy: 0.9080 - val_loss: 0.1999
Epoch 74/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9680 - loss: 0.0722 - val_accuracy: 0.9760 - val_loss: 0.0599
Epoch 75/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9733 - loss: 0.0657 - val_accuracy: 0.9760 - val_loss: 0.0546
Epoch 76/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9773 - loss: 0.0646 - val_accuracy: 0.9760 - val_loss: 0.0606
Epoch 77/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9827 - loss: 0.0596 - val_accuracy: 0.9800 - val_loss: 0.0563
Epoch 78/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9760 - loss: 0.0675 - val_accuracy: 0.9720 - val_loss: 0.0513
Epoch 79/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9733 - loss: 0.0643 - val_accuracy: 0.9720 - val_loss: 0.0543
Epoch 80/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9667 - loss: 0.0702 - val_accuracy: 0.9760 - val_loss: 0.0607
Epoch 81/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9760 - loss: 0.0597 - val_accuracy: 0.9440 - val_loss: 0.0980
Epoch 82/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9773 - loss: 0.0675 - val_accuracy: 0.9760 - val_loss: 0.0524
Epoch 83/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9760 - loss: 0.0606 - val_accuracy: 0.9720 - val_loss: 0.0702
Epoch 84/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9760 - loss: 0.0626 - val_accuracy: 0.9720 - val_loss: 0.0507
Epoch 85/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9760 - loss: 0.0616 - val_accuracy: 0.9800 - val_loss: 0.0501
Epoch 86/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9733 - loss: 0.0604 - val_accuracy: 0.9640 - val_loss: 0.0503
Epoch 87/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9733 - loss: 0.0620 - val_accuracy: 0.9680 - val_loss: 0.0507
Epoch 88/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9733 - loss: 0.0684 - val_accuracy: 0.9720 - val_loss: 0.0505
Epoch 89/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9680 - loss: 0.0678 - val_accuracy: 0.9760 - val_loss: 0.0492
Epoch 90/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9827 - loss: 0.0519 - val_accuracy: 0.9720 - val_loss: 0.0713
Epoch 91/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9760 - loss: 0.0605 - val_accuracy: 0.9720 - val_loss: 0.0504
Epoch 92/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9760 - loss: 0.0566 - val_accuracy: 0.9800 - val_loss: 0.0486
Epoch 93/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9840 - loss: 0.0563 - val_accuracy: 0.9720 - val_loss: 0.0684
Epoch 94/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9813 - loss: 0.0568 - val_accuracy: 0.9680 - val_loss: 0.0488
Epoch 95/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9800 - loss: 0.0607 - val_accuracy: 0.9400 - val_loss: 0.1157
Epoch 96/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9813 - loss: 0.0587 - val_accuracy: 0.9680 - val_loss: 0.0653
Epoch 97/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9747 - loss: 0.0565 - val_accuracy: 0.9640 - val_loss: 0.0708
Epoch 98/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9800 - loss: 0.0556 - val_accuracy: 0.9480 - val_loss: 0.1010
Epoch 99/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9693 - loss: 0.0637 - val_accuracy: 0.9520 - val_loss: 0.0827
Epoch 100/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9707 - loss: 0.0649 - val_accuracy: 0.9720 - val_loss: 0.0490

In [63]:
history_minibatch = model.fit(X_train, y_train, epochs=100, batch_size = 100, verbose=1)

Epoch 1/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9907 - loss: 0.0423
Epoch 2/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9920 - loss: 0.0420
Epoch 3/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0421
Epoch 4/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9933 - loss: 0.0418
Epoch 5/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9933 - loss: 0.0419
Epoch 6/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9920 - loss: 0.0419
Epoch 7/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0418
Epoch 8/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0418
Epoch 9/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0419
Epoch 10/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0418
Epoch 11/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 12/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0418
Epoch 13/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 14/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0418
Epoch 15/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 16/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 17/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0418
Epoch 18/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 19/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0419
Epoch 20/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 21/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 22/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0418
Epoch 23/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 24/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 25/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 26/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 27/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0418
Epoch 28/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9960 - loss: 0.0418
Epoch 29/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 30/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9933 - loss: 0.0417
Epoch 31/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9933 - loss: 0.0417
Epoch 32/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0417
Epoch 33/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0419
Epoch 34/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9947 - loss: 0.0417
Epoch 35/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 36/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0417
Epoch 37/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0418
Epoch 38/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0418
Epoch 39/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9960 - loss: 0.0417
Epoch 40/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9933 - loss: 0.0418
Epoch 41/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9933 - loss: 0.0417
Epoch 42/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 43/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9960 - loss: 0.0417
Epoch 44/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9947 - loss: 0.0417
Epoch 45/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0417
Epoch 46/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9933 - loss: 0.0417
Epoch 47/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0417
Epoch 48/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0417
Epoch 49/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0417
Epoch 50/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0418
Epoch 51/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 52/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0418
Epoch 53/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0417
Epoch 54/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0417
Epoch 55/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0417
Epoch 56/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0417
Epoch 57/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9960 - loss: 0.0416
Epoch 58/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0417
Epoch 59/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0416
Epoch 60/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0417
Epoch 61/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0416
Epoch 62/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0417
Epoch 63/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0416
Epoch 64/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0416
Epoch 65/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0416
Epoch 66/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0416
Epoch 67/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0417
Epoch 68/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0416
Epoch 69/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0416
Epoch 70/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0417
Epoch 71/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0416
Epoch 72/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0417
Epoch 73/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0416
Epoch 74/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0417
Epoch 75/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9960 - loss: 0.0416
Epoch 76/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0417
Epoch 77/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0416
Epoch 78/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0416
Epoch 79/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0416
Epoch 80/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0416
Epoch 81/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9960 - loss: 0.0416
Epoch 82/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0416
Epoch 83/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0416
Epoch 84/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9960 - loss: 0.0416
Epoch 85/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0416
Epoch 86/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9960 - loss: 0.0416
Epoch 87/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9933 - loss: 0.0417
Epoch 88/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9920 - loss: 0.0417
Epoch 89/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9920 - loss: 0.0416
Epoch 90/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9920 - loss: 0.0416
Epoch 91/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0415
Epoch 92/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0415
Epoch 93/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0415
Epoch 94/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0416
Epoch 95/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9960 - loss: 0.0415
Epoch 96/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0415
Epoch 97/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9960 - loss: 0.0415
Epoch 98/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0415
Epoch 99/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9947 - loss: 0.0415
Epoch 100/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9960 - loss: 0.0415

In [64]:
from tensorflow.keras import optimizers

In [66]:
opt = optimizers.SGD(learning_rate=0.01, momentum = 0.9)

In [68]:
model.compile(
    optimizer="sgd",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [69]:
history_full = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=len(X_train),
    verbose=1
)

history = model.fit(
    X_train.values,
    y_train.values,
    validation_data=(X_test.values, y_test.values),
    epochs=100,
    batch_size=1,
    verbose=1
)

history_minibatch = model.fit(X_train, y_train, epochs=100, batch_size = 100, verbose=1)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step - accuracy: 0.9960 - loss: 0.0415
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9960 - loss: 0.0415
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9920 - loss: 0.0417
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9893 - loss: 0.0448
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9560 - loss: 0.0853
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8453 - loss: 0.5663
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5467 - loss: 5.6716
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5880 - loss: 12.6422
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5880 - loss: 4.3453
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6520 - loss: 1.4753
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6360 - loss: 2.1603
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5813 - loss: 2.2476
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6107 - loss: 2.3772
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5600 - loss: 2.8205
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5880 - loss: 3.2339
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6253 - loss: 1.5992
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6253 - loss: 2.0713
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5973 - loss: 1.8590
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6187 - loss: 2.1246
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6040 - loss: 1.7377
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6213 - loss: 1.9828
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6053 - loss: 1.6448
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6227 - loss: 1.8592
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6093 - loss: 1.5555
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6267 - loss: 1.7435
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6133 - loss: 1.4707
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6280 - loss: 1.6354
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6213 - loss: 1.3902
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6307 - loss: 1.5343
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6267 - loss: 1.3139
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6360 - loss: 1.4398
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6387 - loss: 1.2416
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6467 - loss: 1.3514
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6413 - loss: 1.1732
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6533 - loss: 1.2689
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6427 - loss: 1.1087
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6587 - loss: 1.1919
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6493 - loss: 1.0480
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6640 - loss: 1.1201
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6560 - loss: 0.9910
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6680 - loss: 1.0533
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6613 - loss: 0.9375
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6720 - loss: 0.9911
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6680 - loss: 0.8872
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6760 - loss: 0.9332
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6747 - loss: 0.8400
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6813 - loss: 0.8793
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6813 - loss: 0.7957
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6853 - loss: 0.8290
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6907 - loss: 0.7540
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6893 - loss: 0.7821
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6987 - loss: 0.7148
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6973 - loss: 0.7383
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7040 - loss: 0.6779
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7000 - loss: 0.6973
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7147 - loss: 0.6431
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7080 - loss: 0.6590
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7213 - loss: 0.6104
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7107 - loss: 0.6233
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7333 - loss: 0.5797
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7200 - loss: 0.5899
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7347 - loss: 0.5508
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7280 - loss: 0.5588
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7453 - loss: 0.5238
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7373 - loss: 0.5298
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7520 - loss: 0.4986
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7427 - loss: 0.5029
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7613 - loss: 0.4750
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.7467 - loss: 0.4780
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7680 - loss: 0.4530
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7560 - loss: 0.4550
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7747 - loss: 0.4326
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7627 - loss: 0.4337
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.7840 - loss: 0.4138
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7667 - loss: 0.4142
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7960 - loss: 0.3963
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7733 - loss: 0.3962
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8000 - loss: 0.3803
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.7813 - loss: 0.3798
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8067 - loss: 0.3655
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7893 - loss: 0.3648
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8200 - loss: 0.3520
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7933 - loss: 0.3511
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8227 - loss: 0.3396
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7987 - loss: 0.3386
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8360 - loss: 0.3283
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8080 - loss: 0.3273
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8440 - loss: 0.3180
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8120 - loss: 0.3170
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8440 - loss: 0.3086
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8160 - loss: 0.3077
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8493 - loss: 0.3001
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.8293 - loss: 0.2993
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8547 - loss: 0.2924
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8333 - loss: 0.2917
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8560 - loss: 0.2854
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8347 - loss: 0.2848
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.8613 - loss: 0.2791
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8373 - loss: 0.2787
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8613 - loss: 0.2735
Epoch 1/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7200 - loss: 0.5994 - val_accuracy: 0.8240 - val_loss: 0.3871
Epoch 2/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7587 - loss: 0.4825 - val_accuracy: 0.9520 - val_loss: 0.2621
Epoch 3/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7560 - loss: 0.4849 - val_accuracy: 0.8360 - val_loss: 0.3189
Epoch 4/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7653 - loss: 0.4551 - val_accuracy: 0.7960 - val_loss: 0.3686
Epoch 5/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7720 - loss: 0.4391 - val_accuracy: 0.9480 - val_loss: 0.2242
Epoch 6/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8027 - loss: 0.4234 - val_accuracy: 0.6960 - val_loss: 0.5169
Epoch 7/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7973 - loss: 0.4258 - val_accuracy: 0.9160 - val_loss: 0.2409
Epoch 8/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7960 - loss: 0.4154 - val_accuracy: 0.9560 - val_loss: 0.2071
Epoch 9/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7907 - loss: 0.4145 - val_accuracy: 0.9560 - val_loss: 0.2094
Epoch 10/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8000 - loss: 0.4167 - val_accuracy: 0.7160 - val_loss: 0.5538
Epoch 11/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7987 - loss: 0.3938 - val_accuracy: 0.8680 - val_loss: 0.2753
Epoch 12/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7933 - loss: 0.4197 - val_accuracy: 0.8400 - val_loss: 0.3242
Epoch 13/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8000 - loss: 0.3983 - val_accuracy: 0.8200 - val_loss: 0.3512
Epoch 14/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8080 - loss: 0.3805 - val_accuracy: 0.7080 - val_loss: 0.5366
Epoch 15/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8147 - loss: 0.3997 - val_accuracy: 0.8720 - val_loss: 0.2641
Epoch 16/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8173 - loss: 0.3882 - val_accuracy: 0.8680 - val_loss: 0.2692
Epoch 17/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8253 - loss: 0.3786 - val_accuracy: 0.8760 - val_loss: 0.2469
Epoch 18/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8067 - loss: 0.3783 - val_accuracy: 0.9760 - val_loss: 0.1727
Epoch 19/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8373 - loss: 0.3658 - val_accuracy: 0.9280 - val_loss: 0.1944
Epoch 20/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8147 - loss: 0.3748 - val_accuracy: 0.9080 - val_loss: 0.2167
Epoch 21/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8213 - loss: 0.3845 - val_accuracy: 0.7880 - val_loss: 0.3717
Epoch 22/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8373 - loss: 0.3490 - val_accuracy: 0.7640 - val_loss: 0.4488
Epoch 23/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8200 - loss: 0.3739 - val_accuracy: 0.8240 - val_loss: 0.3235
Epoch 24/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8373 - loss: 0.3456 - val_accuracy: 0.9560 - val_loss: 0.1491
Epoch 25/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8200 - loss: 0.3569 - val_accuracy: 0.8880 - val_loss: 0.2587
Epoch 26/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8253 - loss: 0.3590 - val_accuracy: 0.9000 - val_loss: 0.2097
Epoch 27/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8480 - loss: 0.3336 - val_accuracy: 0.9240 - val_loss: 0.2373
Epoch 28/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8320 - loss: 0.3554 - val_accuracy: 0.9560 - val_loss: 0.1584
Epoch 29/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8480 - loss: 0.3484 - val_accuracy: 0.9200 - val_loss: 0.2100
Epoch 30/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8533 - loss: 0.3358 - val_accuracy: 0.7760 - val_loss: 0.4383
Epoch 31/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8400 - loss: 0.3256 - val_accuracy: 0.8320 - val_loss: 0.3369
Epoch 32/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8627 - loss: 0.3152 - val_accuracy: 0.5520 - val_loss: 1.2723
Epoch 33/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8507 - loss: 0.3289 - val_accuracy: 0.9320 - val_loss: 0.1859
Epoch 34/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8520 - loss: 0.3160 - val_accuracy: 0.9320 - val_loss: 0.1857
Epoch 35/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8480 - loss: 0.3271 - val_accuracy: 0.9040 - val_loss: 0.1908
Epoch 36/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8667 - loss: 0.3155 - val_accuracy: 0.8040 - val_loss: 0.3835
Epoch 37/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8613 - loss: 0.3092 - val_accuracy: 0.8520 - val_loss: 0.2806
Epoch 38/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8413 - loss: 0.3265 - val_accuracy: 0.7760 - val_loss: 0.4973
Epoch 39/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8520 - loss: 0.3097 - val_accuracy: 0.8760 - val_loss: 0.2527
Epoch 40/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8613 - loss: 0.3049 - val_accuracy: 0.8440 - val_loss: 0.3245
Epoch 41/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8560 - loss: 0.3068 - val_accuracy: 0.8240 - val_loss: 0.3155
Epoch 42/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8600 - loss: 0.3152 - val_accuracy: 0.9840 - val_loss: 0.1797
Epoch 43/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8640 - loss: 0.3136 - val_accuracy: 0.9280 - val_loss: 0.1730
Epoch 44/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8667 - loss: 0.2963 - val_accuracy: 0.8760 - val_loss: 0.2351
Epoch 45/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8613 - loss: 0.3052 - val_accuracy: 0.6520 - val_loss: 0.9025
Epoch 46/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8587 - loss: 0.2961 - val_accuracy: 0.9760 - val_loss: 0.1294
Epoch 47/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8480 - loss: 0.3154 - val_accuracy: 0.8360 - val_loss: 0.3440
Epoch 48/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8747 - loss: 0.2876 - val_accuracy: 0.7800 - val_loss: 0.5132
Epoch 49/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8680 - loss: 0.3081 - val_accuracy: 0.9720 - val_loss: 0.1525
Epoch 50/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8627 - loss: 0.2886 - val_accuracy: 0.7720 - val_loss: 0.5325
Epoch 51/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8627 - loss: 0.3051 - val_accuracy: 0.9760 - val_loss: 0.1465
Epoch 52/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8600 - loss: 0.2971 - val_accuracy: 0.8720 - val_loss: 0.2466
Epoch 53/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8640 - loss: 0.2947 - val_accuracy: 0.9640 - val_loss: 0.1390
Epoch 54/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8880 - loss: 0.2747 - val_accuracy: 0.8800 - val_loss: 0.2592
Epoch 55/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8880 - loss: 0.2919 - val_accuracy: 0.9200 - val_loss: 0.1985
Epoch 56/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8573 - loss: 0.2920 - val_accuracy: 0.8520 - val_loss: 0.2918
Epoch 57/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8787 - loss: 0.2887 - val_accuracy: 0.9640 - val_loss: 0.1295
Epoch 58/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8680 - loss: 0.2914 - val_accuracy: 0.9600 - val_loss: 0.1330
Epoch 59/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8720 - loss: 0.2848 - val_accuracy: 0.8920 - val_loss: 0.2009
Epoch 60/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8600 - loss: 0.2942 - val_accuracy: 0.9640 - val_loss: 0.1356
Epoch 61/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8520 - loss: 0.3000 - val_accuracy: 0.8560 - val_loss: 0.2719
Epoch 62/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8800 - loss: 0.2709 - val_accuracy: 0.9000 - val_loss: 0.1971
Epoch 63/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8693 - loss: 0.2654 - val_accuracy: 0.8520 - val_loss: 0.2956
Epoch 64/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8653 - loss: 0.2712 - val_accuracy: 0.9240 - val_loss: 0.1551
Epoch 65/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8813 - loss: 0.2567 - val_accuracy: 0.9720 - val_loss: 0.1061
Epoch 66/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8787 - loss: 0.2637 - val_accuracy: 0.9640 - val_loss: 0.1025
Epoch 67/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8880 - loss: 0.2830 - val_accuracy: 0.7880 - val_loss: 0.4903
Epoch 68/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8960 - loss: 0.2587 - val_accuracy: 0.8120 - val_loss: 0.4167
Epoch 69/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8653 - loss: 0.2806 - val_accuracy: 0.9560 - val_loss: 0.2094
Epoch 70/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8827 - loss: 0.2654 - val_accuracy: 0.9160 - val_loss: 0.1928
Epoch 71/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8773 - loss: 0.2597 - val_accuracy: 0.9760 - val_loss: 0.1133
Epoch 72/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8800 - loss: 0.2613 - val_accuracy: 0.9360 - val_loss: 0.1352
Epoch 73/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8880 - loss: 0.2579 - val_accuracy: 0.8520 - val_loss: 0.3010
Epoch 74/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8800 - loss: 0.2766 - val_accuracy: 0.9000 - val_loss: 0.1966
Epoch 75/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8867 - loss: 0.2581 - val_accuracy: 0.6360 - val_loss: 1.1043
Epoch 76/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8933 - loss: 0.2563 - val_accuracy: 0.7880 - val_loss: 0.5474
Epoch 77/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8973 - loss: 0.2589 - val_accuracy: 0.8400 - val_loss: 0.3640
Epoch 78/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8840 - loss: 0.2622 - val_accuracy: 0.9000 - val_loss: 0.1883
Epoch 79/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8880 - loss: 0.2609 - val_accuracy: 0.9480 - val_loss: 0.1360
Epoch 80/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8907 - loss: 0.2532 - val_accuracy: 0.9680 - val_loss: 0.1077
Epoch 81/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8773 - loss: 0.2673 - val_accuracy: 0.8720 - val_loss: 0.2490
Epoch 82/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9000 - loss: 0.2445 - val_accuracy: 0.9680 - val_loss: 0.1171
Epoch 83/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8960 - loss: 0.2369 - val_accuracy: 0.7480 - val_loss: 0.7218
Epoch 84/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8707 - loss: 0.2709 - val_accuracy: 0.9400 - val_loss: 0.1499
Epoch 85/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8840 - loss: 0.2549 - val_accuracy: 0.9480 - val_loss: 0.1364
Epoch 86/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8960 - loss: 0.2493 - val_accuracy: 0.9640 - val_loss: 0.1734
Epoch 87/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8933 - loss: 0.2321 - val_accuracy: 0.9680 - val_loss: 0.0940
Epoch 88/100
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8880 - loss: 0.2544 - val_accuracy: 0.9240 - val_loss: 0.1538
Epoch 89/100